[package]
name = "rawpb"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.4.14",  features = ["derive"]}
rawpb-core = {path = "../rawpb_core"}
hex = "^0.4"
base64 = "0.21.6"
